### ISSUE TITLE
Feat: Async implementation

### ISSUE THREAD

**Issue by spence-s** [privatenumber/get-tsconfig#46]
This lib is great, would there be a chance to support a fully async implementation even though ts doesn't directly support that AFAIK?

**Comment by privatenumber** [comment]
Yes, `typescript` methods are synchronous, so this was also designed to be synchronous to be a drop-in replacement.

Why do you need an async API?

**Comment by spence-s** [comment]
It would be beneficial for performance in some applications and for code style preferences.

**Comment by privatenumber** [comment]
Is there a specific problem you're facing? And how much of a performance gain is it?

**Comment by spence-s** [comment]
No things work fine using it sync - and it's hard to quantify if or what the gain would be without having the async implementation to compare against.

It is quantifiable that if I use sync methods for other operations things slow down a lot. For me this would likely be just a small optimization for particular use cases where lots of files are being linted, but it would be nice to have all the file io be async for everything for my own stylistic preferences.

If you would be open to it, I would be willing to contribute this feature. Which would add an async version of each exported function. Along with analogous async tests.

**Comment by privatenumber** [comment]
I'm not convinced about the benefits of having an async version. In most cases, it can't be used due to limitations like supporting any CommonJS resolution that needs to be synchronous.

I understand that async versions are supposed to be non-blocking and theoretically faster, but I'm a bit skeptical about whether there's any noticeable performance improvement. I've come across reports suggesting that the async version of `fs` is actually slower than its sync counterparts (https://github.com/nodejs/node/issues/41435, https://github.com/nodejs/node/issues/38006, https://github.com/nodejs/node/issues/25741). I'm not sure if I've ever seen anyone demonstrate notable performance gains.

At the moment, it seems like introducing async functionality would only add a significant maintenance burden without any clear justification.

If you have more data that can demonstrate a real performance gain, I'd be interested in taking a look. It would be helpful to see concrete evidence before considering the implementation.

**Comment by spence-s** [comment]
@privatenumber no worries, those reasons make sense. Still, thanks for your work on this package, has been a big help.
