### ISSUE TITLE
Tsconfig Extends + Base Url + Paths Causing Lint Error on 4.7.1

### ISSUE THREAD

**Issue by matthewwolfe** [privatenumber/get-tsconfig#60]
### Problem

Link to reproduction url with steps in readme: https://github.com/matthewwolfe/tsconfig-extends-bug

I have an application that utilizes multiple tsconfigs that extend base tsconfigs that are published as packages separately and available via node_modules. On version 4.7.0 this works perfectly, 4.7.1 introduces an issue where the paths in the base config are not resolved properly. In the repository provided, the `main` branch produces a lint error, the `pinned-version` branch does not produce a lint error.

### Expected behavior

Tsconfigs with base url and paths that are extended should work consistently with tsc

### Minimal reproduction URL

https://github.com/matthewwolfe/tsconfig-extends-bug

### Version

4.7.1

### Node.js version

18.16.0

### Package manager

npm

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Thanks for your report but your reproduction is not minimal and would require further debugging work that may not lead to a get-tsconfig bug. I provide [Priority Support](https://github.com/sponsors/privatenumber) if you need assistance with this.

To make the reproduction minimal, can you make sure `get-tsconfig` and `typescript` are the only dependencies?

Alternatively, feel free to open a PR with a failing test like https://github.com/privatenumber/get-tsconfig/pull/59. This will probably be easier.

Happy to re-open once the bug is demonstrated to be in get-tsconfig.
